//! settlement — Phase 2: ZK proof verification at the moment of receipt
//!
//! # What happens here
//!
//! Phase 1 established that a token has a valid RSA blind signature.
//! Phase 2 adds **zero-knowledge proof of settlement**: the holder proves
//! they possess the (serial, signature) pair without revealing either.
//!
//! The proof is generated by `zk/prove.js` using snarkjs + the compiled
//! Circom circuit.  This module *verifies* that proof using `ark-groth16`
//! — a pure-Rust Groth16 verifier over the BN254 elliptic curve.
//!
//! # The settlement event
//!
//! The moment `settle_token` returns `Ok(true)`, Nothing has classified
//! as a coin.  Not before.
//!
//! # Double-spend prevention
//!
//! Each settlement is bound to a **nullifier** — a Poseidon hash of the
//! serial that uniquely identifies the token without revealing it.
//! The nullifier is stored in `~/.nothing/settled.json`.  If the same
//! nullifier appears twice, the second attempt is rejected.

pub mod verify;

use anyhow::{anyhow, Context, Result};
use std::collections::HashSet;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::settlement::verify::{load_proof_bundle, load_verification_key, verify_groth16};

// ─── Settled-nullifier registry ───────────────────────────────────────────────

fn settled_path() -> Result<PathBuf> {
    let dir = dirs::home_dir()
        .ok_or_else(|| anyhow!("cannot locate home directory"))?
        .join(".nothing");
    fs::create_dir_all(&dir).context("create .nothing dir")?;
    Ok(dir.join("settled.json"))
}

/// Load the set of previously settled nullifiers from disk.
fn load_settled() -> Result<HashSet<String>> {
    let path = settled_path()?;
    if !path.exists() {
        return Ok(HashSet::new());
    }
    let raw = fs::read_to_string(&path).context("read settled.json")?;
    serde_json::from_str(&raw).context("parse settled.json")
}

/// Persist a new nullifier to the settled registry.
fn record_nullifier(nullifier: &str) -> Result<()> {
    let path = settled_path()?;
    let mut settled = load_settled()?;
    settled.insert(nullifier.to_string());
    let mut f = fs::File::create(&path)?;
    writeln!(f, "{}", serde_json::to_string_pretty(&settled)?)?;
    Ok(())
}

// ─── High-level settle entry point ───────────────────────────────────────────

/// Settle a Nothing token.
///
/// Steps:
///   1. Run `node <zk_dir>/prove.js <token_path>` to generate the ZK proof.
///   2. Parse the proof file path from the process output.
///   3. Load the Groth16 verification key from `~/.nothing/settlement/`.
///   4. Verify the proof with ark-groth16.
///   5. Check the nullifier has not been settled before.
///   6. Record the nullifier as settled.
///
/// Returns `Ok(nullifier_hex)` on successful settlement.
pub fn settle_token(token_path: &Path, zk_dir: &Path) -> Result<String> {
    let prove_script = zk_dir.join("prove.js");
    if !prove_script.exists() {
        return Err(anyhow!(
            "ZK prove script not found at {:?}\n\
             Make sure you are running from the Nothing/ project root and\n\
             have run:  cd zk && npm install  and  bash zk/compile.sh",
            prove_script
        ));
    }

    // ── Step 1: Generate the ZK proof via Node.js ─────────────────────────────
    // We call:  node zk/prove.js <token_path>
    // The prove script generates a proof and writes the path to stdout
    // as the line:  PROOF_PATH=<absolute/path/to/proof.json>
    println!("Generating ZK settlement proof...");
    println!("  (This may take 30–120 seconds for RSA-2048 witness computation.)");

    let output = Command::new("node")
        .arg(&prove_script)
        .arg(token_path)
        .output()
        .with_context(|| {
            "Failed to run `node`. Make sure Node.js is installed.\n\
             On macOS: brew install node   or  https://nodejs.org"
        })?;

    // Print the prove.js output so the user can see progress.
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    if !stderr.is_empty() {
        eprintln!("{}", stderr);
    }

    if !output.status.success() {
        return Err(anyhow!(
            "Proof generation failed (exit code {}).\n\
             stdout:\n{}\nstderr:\n{}",
            output.status,
            stdout,
            stderr
        ));
    }

    // Print the human-readable portion of prove.js output (everything before PROOF_PATH=).
    for line in stdout.lines() {
        if !line.starts_with("PROOF_PATH=") {
            println!("{}", line);
        }
    }

    // Parse the proof file path from the last line of stdout.
    let proof_path_str = stdout
        .lines()
        .find(|l| l.starts_with("PROOF_PATH="))
        .ok_or_else(|| anyhow!("prove.js did not output a PROOF_PATH= line"))?
        .strip_prefix("PROOF_PATH=")
        .unwrap()
        .trim();

    let proof_path = PathBuf::from(proof_path_str);

    // ── Step 2: Load the verification key ────────────────────────────────────
    let vk_path = dirs::home_dir()
        .ok_or_else(|| anyhow!("no home dir"))?
        .join(".nothing")
        .join("settlement")
        .join("verification_key.json");

    if !vk_path.exists() {
        return Err(anyhow!(
            "Verification key not found at {:?}\n\
             Run:  node zk/setup.js",
            vk_path
        ));
    }

    let vk = load_verification_key(&vk_path)
        .context("loading Groth16 verification key")?;

    // ── Step 3: Load and parse the proof ─────────────────────────────────────
    let bundle = load_proof_bundle(&proof_path)
        .context("loading proof bundle")?;

    // ── Step 4: Verify the Groth16 proof ─────────────────────────────────────
    // This is the cryptographic binding moment.
    // If the proof is valid, the holder has demonstrated — without revealing
    // the serial or signature — that they possess a legitimately-minted token.
    println!("Verifying Groth16 proof...");

    let valid = verify_groth16(&vk, &bundle)
        .context("Groth16 verification")?;

    if !valid {
        return Err(anyhow!(
            "Proof verification FAILED.\n\
             The proof did not satisfy the settlement circuit constraints."
        ));
    }

    // ── Step 5: Double-spend check ────────────────────────────────────────────
    let nullifier = &bundle.meta.nullifier;
    let settled = load_settled().context("checking nullifier registry")?;

    if settled.contains(nullifier.as_str()) {
        return Err(anyhow!(
            "Settlement REJECTED: nullifier {} has already been settled.\n\
             This token has already been spent.",
            nullifier
        ));
    }

    // ── Step 6: Record the nullifier ─────────────────────────────────────────
    record_nullifier(nullifier).context("recording nullifier")?;

    Ok(nullifier.clone())
}
